languageCode = "en-us"

title = "sapiens.sapide"
theme = "agency-theme"

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) or
	# most longer texts.
	#
	# All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "sapiens.sapide & Stanislas SABATIER"
	description = "Our agency codes and hosts Internet services using free open sources technologies like javascript, meteorJS, GO / golang, freeBSD, email."

	# Since this template is static, the contact form uses www.formspree.io as a
	# proxy. The form makes a POST request to their servers to send the actual
	# email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
	email = "contact@sapienssapide.com"


	# Navigation
	[params.navigation]
		brand = "sapiens.sapide"
		services = "Services"
		technologies = "Technologies"
		portfolio = "Works"
		contact = "Contact"

    # Add custom links. Those can be pre- and postpended to the default menu above.
    # Use the weight attribute to order your custom links. Uncomment the example
    # below and replace the values with your own.

    # prepended links
    #[[menu.prepend]]
    #    url = "http://gohugo.io"
    #    name = "Hugo"
    #    weight = 10

    # postpended links
    [[menu.postpend]]
        url = "https://twitter.com/sapienSSapide"
        name = "twitter"
        pre = "<i class='fa fa-twitter'></i>"
        weight = 10

    [[menu.postpend]]
        url = "https://github.com/sapiens-sapide"
        name = "github"
        pre = "<i class='fa fa-github'></i>"
        weight = 20

    [[menu.postpend]]
        url = "https://git.sapienssapide.com:3000/explore"
        name = "git"
        pre = "<i class='fa fa-git'></i>"
        weight = 30

	# Hero section
	[params.hero]
		# To change the background image of the hero, replace 'header-bg.jpg' in
		# the 'static/img' folder.
		title = "Since 2008, we code and host Internet services and applications.\n\nWe rely on free and open source technologies only."
		subtitle = ""
		buttonText = "More"

	# Services section
	[params.services]
        enable = true
		title = "Our services"
		subtitle = "We are coding and **hosting** :"

        [[params.services.row]]

            [[params.services.row.list]]
                icon = "fa-globe"
                title = "Websites"
                description = "we work with freelances and design agencies for visual identity"

            [[params.services.row.list]]
                icon = "fa-mobile"
                title = "Mobile applications"
                description = "for professionals and consumers"

            [[params.services.row.list]]
                icon = "fa-tachometer"
                title = "Business management softwares"
                description = "quality control, dashboards, business services…"

            [[params.services.row.list]]
                icon = "fa-database"
                title = "Databases"
                description = "design, implementation, interfaces and hosting"

    # Technologies section
	[params.technologies]
        enable = true
		title = "Our technologies"
		subtitle = ""

        [[params.technologies.row]]

            [[params.technologies.row.list]]
                title = "Main languages"
                description = "Javascript, Go, C"
                img = "gopher.png"

            [[params.technologies.row.list]]
                title = "Frameworks"
                description = "meteorJS, nodeJS, wordpress, cordova, hugo"

            [[params.technologies.row.list]]
                title = "Databases"
                description = "mongoDB, postgreSQL, sqlcipher"

            [[params.technologies.row.list]]
                title = "CSS frameworks"
                description = "bootstrap, semantic-ui, foundation"

            [[params.technologies.row.list]]
                title = "hosting & system administration"
                description = "freeBSD only, one of the most reliable OS in the worls !"
                img = "logo-freebsd.png"

            [[params.technologies.row.list]]
                title = "and : "
                description = "postfix, dovecot, apache, nginx, roundcube, webDAV…"

	# Portfolio section
	[params.portfolio]
        enable = true
		# All projects defined in their own files. You can find example projects
		# at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
		# at the root of this Hugo site.
		# For more informtion take a look at the README.
		title = "Last works"
		subtitle = ""

	# Client section
    [params.clients_list]
        enable = true

    	# All the clients' logos are stored under 'static/img/logos'.
    	# Replace them with your clients's logos.
    	[[params.clients]]
    		logo = "marianne.jpg"
    		link = "http://www.marianne.net"

    	[[params.clients]]
    		logo = "nealite.jpg"
    		link = "http://www.nealite.fr"

    	[[params.clients]]
    		logo = "area17.png"
    		link = "http://www.area17.com"

    	[[params.clients]]
    		logo = "swad.jpg"
    		link = "http://www.swad.fr"

    	[[params.clients]]
    		logo = "wan-ifra.png"
    		link = "http://www.wan-ifra.org"

        [[params.clients]]
            logo = "npa-conseil.png"
            link = "http://www.npaconseil.com/"

    	[[params.clients]]
    		logo = "delormeau.png"
    		link = "http://www.delormeau.eu/"

    	[[params.clients]]
    		logo = "lefigaro.png"
    		link = "http://www.lefigaro.fr"

    	[[params.clients]]
    		logo = "concept-recrutement.png"
    		link = "http://www.concept-recrutement.fr/"


	# Contact section
	[params.contact]
        enable = true
		title = "Contact"
		subtitle  = ""
		buttonText = "Send your message"

		# 'warning' defines error messages for invalid inputs
		[params.contact.form.name]
			text = "Name *"
			warning = "Please, fill in your name"

		[params.contact.form.email]
			text = "E-mail *"
			warning = "Please fill in your email"

		[params.contact.form.phone]
			text = "Phone # *"
			warning = "Please fill in a phone number"

		[params.contact.form.message]
			text = "Your Message *"
			warning = "Please enter a message"


	# Footer section
	[params.footer]
        enable = true
		copyright = ""

		[[params.footer.social]]
			icon = "fa-twitter"
			link = "https://twitter.com/sapienSSapide"

		[[params.footer.social]]
			icon = "fa-linkedin"
			link = "https://www.linkedin.com/in/stansabatier"

		[[params.footer.social]]
			icon = "fa-github"
			link = "https://github.com/sapiens-sapide"

		[[params.footer.social]]
			icon = "fa-git"
			link = "https://git.sapienssapide.com:300/explore"
